### PR TITLE
Added a Division Function

### PR DESCRIPTION
**Pull request by tzvetd**
Added a simple division function to divide by an input
@ejgl

### CODE REVIEW

**Review by ejgl — APPROVED** [review]
There seems to be a few problems - check out my most recent comment!

**Review by ejgl — CHANGES_REQUESTED** [review]
There's a few changes you need to make, when I tested it with the numbers 15 and 5, it did not return 3. It works with fractions, but when I try to get whole number quotients, it does not work. Another example is 6 and 3: submitting ./scicalc 6 3 returns .055

**Comment by tzvetd** [comment]
Thanks for finding these issues! I've gone through and fixed these problems, and the div function should be working properly now. Thanks!

**Comment by ejgl** [comment]
Yup, seems fixed. LGTM!

**Pull request merged**
